CREATE DATABASE TestDB;
GO

USE TestDB;
GO

CREATE TABLE Inventory (id INT IDENTITY(1,1) PRIMARY KEY, name NVARCHAR(50), quantity INT);
GO

INSERT INTO Inventory VALUES ('banana', 150); INSERT INTO Inventory VALUES ('orange', 154);
GO